services:
  app:
    image: robinalfengard/user-servicev4:1.5
    depends_on:
      - mysql
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userdatabase
      SPRING_DATASOURCE_USERNAME: developer
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PlATFORM: mysql
    restart: on-failure

  mysql:
    image: 'mysql:8.3.0'
    environment:
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: developer
      MYSQL_DATABASE: userdatabase
    ports:
      - '3306:3306'

  message-db:
    image: 'mongo:latest'
    environment:
      MONGO_DB_USERNAME: developer
      MONGO_DB_PASSWORD: secret
      MONGO_DB_DATABASE: messagedatabase
    ports:
      - '27017:27017'

  message-service:
    image: 'ghcr.io/chatgut/micropostservice:main'
    ports:
      - '8000:8000'
    environment:
      ROCKET_DATABASES: '{postservice={url="mongodb://mongo-db:27017/messagedatabase"}}'
      ROCKET_RABBIT_HOST: "amqp://rabitmq:5672"

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '15672:15672'
      - '5672:5672'

  frontend:
    image: 'ghcr.io/chatgut/frontend:0.0.3'
    ports:
      - '8080:8080'


  image-service:
    image: 'ghcr.io/chatgut/imageservicebov:sha-925024f'
    depends_on:
      - image-database
    ports:
      - "8001:8001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://image-database:3306/imagedatabase
      SPRING_DATASOURCE_USERNAME: developer
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PLATFORM: image-database
    restart: on-failure

  image-database:
    image: 'mysql:8.3.0'
    environment:
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: developer
      MYSQL_DATABASE: imagedatabase
    ports:
      - '3309:3306'