apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      role: user-api
  template:
    metadata:
      labels:
        role: user-api
    spec:
      containers:
        - name: user-service
          image: robinalfengard/user-servicev4:1.5
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/userdatabase
            - name: SPRING_DATASOURCE_USERNAME
              value: developer
            - name: SPRING_DATASOURCE_PASSWORD
              value: secret
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_PLATFORM
              value: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      role: db
  template:
    metadata:
      labels:
        role: db
    spec:
      containers:
        - name: mysql
          image: 'mysql:8.3.0'
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_PASSWORD
              value: secret
            - name: MYSQL_ROOT_PASSWORD
              value: secret
            - name: MYSQL_USER
              value: developer
            - name: MYSQL_DATABASE
              value: userdatabase